/// Integration tests for backend-python.
///
/// The backend emits 3 files:
///   files[0] = pyproject.toml
///   files[1] = src/<module>.py
///   files[2] = tests/test_roundtrip.py

use std::path::PathBuf;
use backend_python::PythonBackend;
use cddlc_codegen::{Backend, CodegenOptions};
use cddlc_ir::lower;
use cddlc_parser::parse_cddl;

struct GeneratedPackage {
    pyproject: String,
    source:    String,
    tests:     String,
}

fn compile(src: &str) -> GeneratedPackage {
    compile_with_opts(src, CodegenOptions::default())
}

fn compile_with_opts(src: &str, opts: CodegenOptions) -> GeneratedPackage {
    let parsed  = parse_cddl(src, PathBuf::from("test.cddl")).expect("parse");
    let lowered = lower(&parsed.value, 16, 64).expect("lower");
    let out     = PythonBackend.generate(&lowered.module, &opts).expect("generate");
    assert_eq!(out.files.len(), 3, "expected 3 output files");
    GeneratedPackage {
        pyproject: out.files[0].content.clone(),
        source:    out.files[1].content.clone(),
        tests:     out.files[2].content.clone(),
    }
}

// ── Package structure ─────────────────────────────────────────────────────────

#[test]
fn test_emits_three_files() {
    let opts   = CodegenOptions::default();
    let parsed = parse_cddl("x = uint", PathBuf::from("t.cddl")).unwrap();
    let lowered = lower(&parsed.value, 16, 64).unwrap();
    let out    = PythonBackend.generate(&lowered.module, &opts).unwrap();
    assert_eq!(out.files.len(), 3);
    assert!(out.files[0].path.ends_with("pyproject.toml"));
    assert!(out.files[1].path.ends_with(".py"));
    assert!(out.files[2].path.ends_with("test_roundtrip.py"));
}

#[test]
fn test_crate_dir_named_after_module() {
    let opts   = CodegenOptions::default();
    let parsed = parse_cddl("x = uint", PathBuf::from("sensor.cddl")).unwrap();
    let lowered = lower(&parsed.value, 16, 64).unwrap();
    let out    = PythonBackend.generate(&lowered.module, &opts).unwrap();
    assert!(out.files[0].path.starts_with("sensor-cbor/"));
    assert!(out.files[1].path.starts_with("sensor-cbor/src/"));
    assert!(out.files[2].path.starts_with("sensor-cbor/tests/"));
}

// ── pyproject.toml ────────────────────────────────────────────────────────────

#[test]
fn test_pyproject_generated_comment() {
    let g = compile("x = uint");
    assert!(g.pyproject.contains("@generated by cddlc"));
}

#[test]
fn test_pyproject_python_version() {
    let g = compile("x = uint");
    assert!(g.pyproject.contains(">=3.11"));
}

#[test]
fn test_pyproject_cbor2_dependency() {
    let g = compile("x = uint");
    assert!(g.pyproject.contains("cbor2"));
}

#[test]
fn test_pyproject_pytest_dev_dependency() {
    let g = compile("x = uint");
    assert!(g.pyproject.contains("pytest"));
}

#[test]
fn test_pyproject_pep517_build_system() {
    let g = compile("x = uint");
    assert!(g.pyproject.contains("[build-system]"));
    assert!(g.pyproject.contains("setuptools"));
}

// ── Source file ───────────────────────────────────────────────────────────────

#[test]
fn test_source_generated_comment() {
    let g = compile("x = uint");
    assert!(g.source.contains("@generated by cddlc"));
}

#[test]
fn test_source_future_annotations() {
    let g = compile("x = uint");
    assert!(g.source.contains("from __future__ import annotations"));
}

#[test]
fn test_source_imports_cbor2() {
    let g = compile("x = uint");
    assert!(g.source.contains("import cbor2"));
}

#[test]
fn test_source_imports_dataclass() {
    let g = compile("sensor = { id: uint }");
    assert!(g.source.contains("from dataclasses import dataclass"));
}

#[test]
fn test_dcbor_comment() {
    let mut opts = CodegenOptions::default();
    opts.dcbor = true;
    let g = compile_with_opts("s = { b: uint, a: tstr }", opts);
    assert!(g.source.contains("deterministic") || g.source.contains("dCBOR"));
}

// ── Struct ────────────────────────────────────────────────────────────────────

#[test]
fn test_struct_is_dataclass() {
    let g = compile("sensor = { id: uint, value: float32 }");
    assert!(g.source.contains("@dataclass"));
    assert!(g.source.contains("class Sensor:"));
}

#[test]
fn test_struct_uint_field() {
    let g = compile("sensor = { id: uint }");
    assert!(g.source.contains("id: int"));
}

#[test]
fn test_struct_float_field() {
    let g = compile("sensor = { value: float32 }");
    assert!(g.source.contains("value: float"));
}

#[test]
fn test_struct_tstr_field() {
    let g = compile("msg = { label: tstr }");
    assert!(g.source.contains("label: str"));
}

#[test]
fn test_struct_optional_field() {
    let g = compile("msg = { id: uint, ? label: tstr }");
    assert!(g.source.contains("Optional[str]"));
}

#[test]
fn test_struct_repeated_field_is_list() {
    let g = compile("msg = { id: uint, * tag: tstr }");
    assert!(g.source.contains("list[str]"));
}

#[test]
fn test_struct_has_encode_method() {
    let g = compile("sensor = { id: uint }");
    assert!(g.source.contains("def encode(self) -> bytes:"));
}

#[test]
fn test_struct_has_decode_classmethod() {
    let g = compile("sensor = { id: uint }");
    assert!(g.source.contains("@classmethod"));
    assert!(g.source.contains("def decode(cls, data: bytes)"));
}

#[test]
fn test_struct_encode_uses_cbor2_dumps() {
    let g = compile("sensor = { id: uint }");
    assert!(g.source.contains("cbor2.dumps"));
}

#[test]
fn test_struct_encode_builds_map() {
    let g = compile("sensor = { id: uint }");
    assert!(g.source.contains("_map = {"));
    assert!(g.source.contains("\"id\""));
}

#[test]
fn test_struct_decode_uses_cbor2_loads() {
    let g = compile("sensor = { id: uint }");
    assert!(g.source.contains("cbor2.loads(data)"));
}

#[test]
fn test_struct_decode_checks_dict() {
    let g = compile("sensor = { id: uint }");
    assert!(g.source.contains("isinstance(raw, dict)"));
}

#[test]
fn test_struct_with_ref() {
    let g = compile("device-id = uint\nsensor = { id: device-id }");
    assert!(g.source.contains("id: DeviceId"));
}

#[test]
fn test_struct_optional_uses_spread() {
    let g = compile("msg = { id: uint, ? label: tstr }");
    // Optional fields use spread operator pattern
    assert!(g.source.contains("if self.label is not None"));
}

// ── Tagged struct ─────────────────────────────────────────────────────────────

#[test]
fn test_tagged_struct_encode_cbor_tag() {
    let g = compile("tagged-sensor = #6.100({ id: uint })");
    assert!(g.source.contains("CBORTag(100"));
}

#[test]
fn test_tagged_struct_decode_verifies_tag() {
    let g = compile("tagged-sensor = #6.100({ id: uint })");
    assert!(g.source.contains("CBORTag") && g.source.contains("100"));
    assert!(g.source.contains("raise ValueError"));
}

// ── Enum (dataclass with kind field) ─────────────────────────────────────────

#[test]
fn test_enum_is_dataclass() {
    let g = compile(r#"status = "ok" / "warn" / "error""#);
    assert!(g.source.contains("@dataclass"));
    assert!(g.source.contains("class Status:"));
}

#[test]
fn test_enum_has_kind_field() {
    let g = compile(r#"status = "ok" / "warn""#);
    assert!(g.source.contains("kind:"));
    assert!(g.source.contains("Literal["));
}

#[test]
fn test_enum_has_named_constructors() {
    let g = compile(r#"status = "ok" / "warn""#);
    assert!(g.source.contains("def make_Ok(cls)") || g.source.contains("make_Ok"));
    assert!(g.source.contains("def make_Warn(cls)") || g.source.contains("make_Warn"));
}

#[test]
fn test_enum_encode_uses_match() {
    let g = compile(r#"status = "ok" / "warn""#);
    assert!(g.source.contains("match self.kind:"));
}

#[test]
fn test_enum_decode_checks_string() {
    let g = compile(r#"status = "ok" / "warn""#);
    assert!(g.source.contains("isinstance(raw, str)"));
    assert!(g.source.contains("\"ok\"") || g.source.contains("'ok'"));
}

#[test]
fn test_enum_decode_has_classmethod() {
    let g = compile(r#"status = "ok" / "warn""#);
    assert!(g.source.contains("@classmethod") && g.source.contains("def decode"));
}

// ── Array ─────────────────────────────────────────────────────────────────────

#[test]
fn test_array_is_dataclass_with_items() {
    let g = compile("readings = [* float32]");
    assert!(g.source.contains("@dataclass"));
    assert!(g.source.contains("items: list[float]"));
}

#[test]
fn test_array_uses_default_factory() {
    let g = compile("readings = [* uint]");
    assert!(g.source.contains("default_factory=list"));
}

#[test]
fn test_array_encode_dumps_items() {
    let g = compile("readings = [* uint]");
    assert!(g.source.contains("cbor2.dumps(self.items)"));
}

#[test]
fn test_array_decode_checks_list() {
    let g = compile("readings = [* uint]");
    assert!(g.source.contains("isinstance(raw, list)"));
}

// ── Alias ─────────────────────────────────────────────────────────────────────

#[test]
fn test_simple_alias_is_dataclass() {
    let g = compile("device-id = uint");
    assert!(g.source.contains("@dataclass"));
    assert!(g.source.contains("class DeviceId:"));
    assert!(g.source.contains("value: int"));
}

#[test]
fn test_constrained_alias_has_post_init() {
    let g = compile("device-id = tstr .size 16");
    assert!(g.source.contains("def __post_init__"));
}

#[test]
fn test_constrained_alias_validates_length() {
    let g = compile("device-id = tstr .size 16");
    assert!(g.source.contains("len(self.value) == 16"));
    assert!(g.source.contains("raise ValueError"));
}

#[test]
fn test_range_constraint_validation() {
    let g = compile("temp = int .ge -40 .le 85");
    assert!(g.source.contains("-40") && g.source.contains("85"));
    assert!(g.source.contains("raise ValueError"));
}

#[test]
fn test_tagged_alias_encode_cbor_tag() {
    let g = compile("timestamp = #6.1(uint)");
    assert!(g.source.contains("CBORTag(1"));
}

#[test]
fn test_tagged_alias_decode_verifies_tag() {
    let g = compile("timestamp = #6.1(uint)");
    assert!(g.source.contains("CBORTag") && g.source.contains("raise ValueError"));
}

// ── dCBOR ─────────────────────────────────────────────────────────────────────

#[test]
fn test_dcbor_sorts_keys() {
    let mut opts = CodegenOptions::default();
    opts.dcbor = true;
    let g = compile_with_opts("s = { b: uint, a: tstr }", opts);
    let a_pos = g.source.find("\"a\"").unwrap_or(usize::MAX);
    let b_pos = g.source.find("\"b\"").unwrap_or(0);
    assert!(a_pos < b_pos, "dCBOR: 'a' should be encoded before 'b'");
}

// ── Test file ─────────────────────────────────────────────────────────────────

#[test]
fn test_roundtrip_generated_comment() {
    let g = compile("x = uint");
    assert!(g.tests.contains("@generated by cddlc"));
}

#[test]
fn test_roundtrip_imports_pytest() {
    let g = compile("sensor = { id: uint }");
    assert!(g.tests.contains("import pytest"));
}

#[test]
fn test_roundtrip_imports_from_module() {
    let g = compile("sensor = { id: uint }");
    assert!(g.tests.contains("from ") && g.tests.contains("import"));
    assert!(g.tests.contains("Sensor"));
}

#[test]
fn test_roundtrip_struct_test_class() {
    let g = compile("sensor = { id: uint, value: float32 }");
    assert!(g.tests.contains("class TestSensor:"));
}

#[test]
fn test_roundtrip_struct_default_test() {
    let g = compile("sensor = { id: uint }");
    assert!(g.tests.contains("def test_roundtrip_default(self)"));
    assert!(g.tests.contains("Sensor("));
    assert!(g.tests.contains(".encode()"));
    assert!(g.tests.contains(".decode("));
}

#[test]
fn test_roundtrip_struct_explicit_test() {
    let g = compile("sensor = { id: uint }");
    assert!(g.tests.contains("def test_roundtrip_explicit(self)"));
}

#[test]
fn test_roundtrip_uses_assert() {
    let g = compile("sensor = { id: uint }");
    assert!(g.tests.contains("assert decoded."));
}

#[test]
fn test_roundtrip_enum_per_variant() {
    let g = compile(r#"status = "ok" / "warn""#);
    // Variant names are PascalCase from IR (Ok, Warn) then snake_cased
    assert!(g.tests.contains("test_roundtrip_ok") || g.tests.contains("test_roundtrip_Ok"));
    assert!(g.tests.contains("test_roundtrip_warn") || g.tests.contains("test_roundtrip_Warn"));
}

#[test]
fn test_roundtrip_alias_valid_and_invalid() {
    let g = compile("device-id = tstr .size 16");
    assert!(g.tests.contains("test_roundtrip_valid"));
    assert!(g.tests.contains("test_invalid_raises"));
    assert!(g.tests.contains("pytest.raises(ValueError)"));
}

#[test]
fn test_roundtrip_array_empty() {
    let g = compile("readings = [* float32]");
    assert!(g.tests.contains("TestReadings"));
    assert!(g.tests.contains("test_roundtrip_empty"));
}

#[test]
fn test_iot_schema() {
    let g = compile(r#"
sensor-message = {
    version:   uint,
    device-id: device-id,
    timestamp: timestamp,
}
device-id = tstr .size 16
timestamp = #6.1(uint)
"#);
    assert!(g.source.contains("class SensorMessage:"));
    assert!(g.source.contains("class DeviceId:"));
    assert!(g.source.contains("len(self.value) == 16"));
    assert!(g.source.contains("CBORTag(1"));
}
