/// Python backend for cddlc.
///
/// Emits a Python package:
///   <module>-cbor/
///     pyproject.toml            ← PEP 517, cbor2, pytest
///     src/<module>.py           ← dataclasses + encode/decode
///     tests/test_roundtrip.py   ← pytest roundtrip tests

use cddlc_codegen::{
    to_pascal_case, to_snake_case,
    Backend, CodegenError, CodegenOptions, CodegenOutput, GeneratedFile,
    IndentWriter,
};
use cddlc_ir::{
    AliasDef, ArrayDef, Constraint, EnumDef,
    IrModule, LiteralValue, Occurrence, Primitive, StructDef, TypeDef, TypeRef,
};

pub struct PythonBackend;

impl Backend for PythonBackend {
    fn language_name(&self) -> &str { "Python" }
    fn file_extension(&self) -> &str { "py" }

    fn generate(
        &self,
        module: &IrModule,
        opts:   &CodegenOptions,
    ) -> Result<CodegenOutput, CodegenError> {
        let name      = module.name.as_str();
        let crate_dir = format!("{name}-cbor");
        let mod_name  = py_module_name(name);

        Ok(CodegenOutput {
            files: vec![
                GeneratedFile {
                    path:    format!("{crate_dir}/pyproject.toml"),
                    content: emit_pyproject(name),
                },
                GeneratedFile {
                    path:    format!("{crate_dir}/src/{mod_name}.py"),
                    content: emit_source(module, opts),
                },
                GeneratedFile {
                    path:    format!("{crate_dir}/tests/test_roundtrip.py"),
                    content: emit_tests(module, opts),
                },
            ],
        })
    }
}

// ── pyproject.toml ────────────────────────────────────────────────────────────

fn emit_pyproject(name: &str) -> String {
    let pkg_name = name.replace('_', "-");
    format!(r#"# @generated by cddlc — do not edit manually
[build-system]
requires      = ["setuptools>=68"]
build-backend = "setuptools.backends.legacy:build"

[project]
name        = "{pkg_name}-cbor"
version     = "0.1.0"
description = "@generated by cddlc"
requires-python = ">=3.11"
dependencies = [
    "cbor2>=5.6",
]

[project.optional-dependencies]
dev = [
    "pytest>=8.0",
    "pytest-cov>=5.0",
]

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.setuptools.packages.find]
where = ["src"]
"#)
}

// ── Source file ───────────────────────────────────────────────────────────────

fn emit_source(module: &IrModule, opts: &CodegenOptions) -> String {
    let mut w = IndentWriter::new(4);

    w.line("# @generated by cddlc — do not edit manually");
    if opts.dcbor { w.line("# Encoding: deterministic (dCBOR)"); }
    w.line("from __future__ import annotations");
    w.blank();
    w.line("import cbor2");
    w.line("from dataclasses import dataclass, field");
    w.line("from typing import Literal, Optional");
    w.blank();

    for (_, def) in &module.types {
        emit_type(&mut w, def, opts);
        w.blank();
    }

    w.finish()
}

fn emit_type(w: &mut IndentWriter, def: &TypeDef, opts: &CodegenOptions) {
    match def {
        TypeDef::Struct(s) => emit_struct(w, s, opts),
        TypeDef::Enum(e)   => emit_enum(w, e, opts),
        TypeDef::Array(a)  => emit_array(w, a, opts),
        TypeDef::Alias(a)  => emit_alias(w, a, opts),
        TypeDef::Map(_)    => {}
    }
}

// ── Struct ────────────────────────────────────────────────────────────────────

fn emit_struct(w: &mut IndentWriter, s: &StructDef, opts: &CodegenOptions) {
    if let Some(doc) = s.doc.as_deref() { w.line(&format!("# {doc}")); }
    if s.deprecated { w.line("# @deprecated"); }

    let class_name = to_pascal_case(&s.name);
    w.line("@dataclass");
    w.line(&format!("class {class_name}:"));
    w.indent();

    for f in &s.fields {
        if let Some(doc) = f.doc.as_deref() { w.line(&format!("# {doc}")); }
        let py_type = py_field_type(&f.ty, &f.occurrence, opts);
        let fname   = to_snake_case(&f.name);
        match &f.occurrence {
            Occurrence::Optional => {
                w.line(&format!("{fname}: {py_type} = None"));
            }
            Occurrence::ZeroOrMore { .. } | Occurrence::OneOrMore { .. }
            | Occurrence::Bounded { .. } => {
                w.line(&format!("{fname}: {py_type} = field(default_factory=list)"));
            }
            Occurrence::Required => {
                w.line(&format!("{fname}: {py_type}"));
            }
        }
    }
    w.blank();
    emit_struct_encode(w, s, opts);
    w.blank();
    emit_struct_decode(w, s, &class_name, opts);

    w.dedent();
}

fn emit_struct_encode(w: &mut IndentWriter, s: &StructDef, opts: &CodegenOptions) {
    w.line("def encode(self) -> bytes:");
    w.indent();

    let fields: Vec<_> = if opts.dcbor {
        let mut fs: Vec<_> = s.fields.iter().collect();
        fs.sort_by(|a, b| a.name.cmp(&b.name));
        fs
    } else {
        s.fields.iter().collect()
    };

    w.line("_map = {");
    w.indent();
    for f in &fields {
        let fname = to_snake_case(&f.name);
        let key   = f.name.as_str();
        match &f.occurrence {
            Occurrence::Optional => {
                w.line(&format!("**({{{:?}: self.{fname}}} if self.{fname} is not None else {{}}),", key));
            }
            _ => {
                w.line(&format!("{:?}: self.{fname},", key));
            }
        }
    }
    w.dedent();
    w.line("}");

    if let Some(tag) = s.tagged {
        w.line(&format!("return cbor2.dumps(cbor2.CBORTag({}, _map))", tag.0));
    } else {
        w.line("return cbor2.dumps(_map)");
    }
    w.dedent();
}

fn emit_struct_decode(w: &mut IndentWriter, s: &StructDef, class_name: &str, opts: &CodegenOptions) {
    w.line("@classmethod");
    w.line(&format!("def decode(cls, data: bytes) -> \"{class_name}\":"));
    w.indent();
    w.line("raw = cbor2.loads(data)");

    if let Some(tag) = s.tagged {
        w.line(&format!("if not isinstance(raw, cbor2.CBORTag) or raw.tag != {}:", tag.0));
        w.indent();
        w.line("raise ValueError(\"Unexpected CBOR tag\")");
        w.dedent();
        w.line("raw = raw.value");
    }

    w.line("if not isinstance(raw, dict):");
    w.indent();
    w.line("raise ValueError(\"Expected CBOR map\")");
    w.dedent();

    w.line(&format!("return cls("));
    w.indent();
    for f in &s.fields {
        let fname = to_snake_case(&f.name);
        let key   = f.name.as_str();
        match &f.occurrence {
            Occurrence::Optional => {
                let conv = py_convert_expr(&f.ty, &format!("raw[{key:?}]"), opts);
                w.line(&format!("{fname}={conv} if {key:?} in raw else None,"));
            }
            _ => {
                let conv = py_convert_expr(&f.ty, &format!("raw[{key:?}]"), opts);
                if f.constraints.is_empty() {
                    w.line(&format!("{fname}={conv},"));
                } else {
                    w.line(&format!("{fname}=cls._validate_{fname}({conv}),"));
                }
            }
        }
    }
    w.dedent();
    w.line(")");

    // Validation helper methods for constrained fields
    for f in &s.fields {
        if !f.constraints.is_empty() {
            let fname = to_snake_case(&f.name);
            let ftype = py_typeref(&f.ty, opts);
            w.blank();
            w.line("@staticmethod");
            w.line(&format!("def _validate_{fname}(v: {ftype}) -> {ftype}:"));
            w.indent();
            for c in &f.constraints {
                if let Some(check) = py_constraint_check(c, "v") {
                    let msg = py_constraint_description(c);
                    w.line(&format!("if not ({check}):"));
                    w.indent();
                    w.line(&format!("raise ValueError({msg:?})"));
                    w.dedent();
                }
            }
            w.line("return v");
            w.dedent();
        }
    }

    w.dedent();
}

// ── Enum ──────────────────────────────────────────────────────────────────────

fn emit_enum(w: &mut IndentWriter, e: &EnumDef, _opts: &CodegenOptions) {
    if let Some(doc) = e.doc.as_deref() { w.line(&format!("# {doc}")); }
    if e.deprecated { w.line("# @deprecated"); }

    let class_name = to_pascal_case(&e.name);

    let kinds: Vec<String> = e.variants.iter()
        .map(|v| format!("{:?}", to_pascal_case(&v.name)))
        .collect();
    let kind_type = if kinds.len() == 1 {
        format!("Literal[{}]", kinds[0])
    } else {
        format!("Literal[{}]", kinds.join(", "))
    };

    let value_types: Vec<String> = {
        let mut seen = std::collections::HashSet::new();
        e.variants.iter()
            .filter_map(|v| match &v.ty {
                TypeRef::Primitive(Primitive::Null) => None,
                TypeRef::Primitive(p) => Some(py_primitive(p).to_owned()),
                TypeRef::Named(n) => Some(to_pascal_case(n)),
                _ => None,
            })
            .filter(|t| seen.insert(t.clone()))
            .collect()
    };

    let value_annotation = if value_types.is_empty() {
        "None".into()
    } else if value_types.len() == 1 {
        format!("{} | None", value_types[0])
    } else {
        format!("{} | None", value_types.join(" | "))
    };

    w.line("@dataclass");
    w.line(&format!("class {class_name}:"));
    w.indent();
    w.line(&format!("kind: {kind_type}"));
    w.line(&format!("value: {value_annotation} = None"));
    w.blank();

    // Named constructors
    for v in &e.variants {
        let vname    = to_pascal_case(&v.name);
        match &v.ty {
            TypeRef::Primitive(Primitive::Null | Primitive::Tstr) => {
                w.line("@classmethod");
                w.line(&format!("def make_{vname}(cls) -> \"{class_name}\":"));
                w.indent();
                w.line(&format!("return cls(kind={vname:?})"));
                w.dedent();
                w.blank();
            }
            TypeRef::Primitive(p) => {
                let pt = py_primitive(p);
                w.line("@classmethod");
                w.line(&format!("def make_{vname}(cls, value: {pt}) -> \"{class_name}\":"));
                w.indent();
                w.line(&format!("return cls(kind={vname:?}, value=value)"));
                w.dedent();
                w.blank();
            }
            TypeRef::Named(n) => {
                let ct = to_pascal_case(n);
                w.line("@classmethod");
                w.line(&format!("def make_{vname}(cls, value: {ct}) -> \"{class_name}\":"));
                w.indent();
                w.line(&format!("return cls(kind={vname:?}, value=value)"));
                w.dedent();
                w.blank();
            }
            _ => {}
        }
    }

    // encode
    w.line("def encode(self) -> bytes:");
    w.indent();
    w.line("match self.kind:");
    w.indent();
    for v in &e.variants {
        let vname    = to_pascal_case(&v.name);
        let cddl_str = v.name.to_lowercase().replace('_', "-");
        w.line(&format!("case {vname:?}:"));
        w.indent();
        match &v.ty {
            TypeRef::Primitive(Primitive::Null | Primitive::Tstr) => {
                if let Some(tag) = e.tagged {
                    w.line(&format!("return cbor2.dumps(cbor2.CBORTag({}, {cddl_str:?}))", tag.0));
                } else {
                    w.line(&format!("return cbor2.dumps({cddl_str:?})"));
                }
            }
            TypeRef::Primitive(_) => {
                if let Some(tag) = e.tagged {
                    w.line(&format!("return cbor2.dumps(cbor2.CBORTag({}, self.value))", tag.0));
                } else {
                    w.line("return cbor2.dumps(self.value)");
                }
            }
            TypeRef::Named(_) => {
                w.line("assert self.value is not None");
                w.line("return self.value.encode()");
            }
            _ => {
                w.line("return cbor2.dumps(None)");
            }
        }
        w.dedent();
    }
    w.dedent();
    w.line("raise ValueError(f\"Unknown kind: {self.kind}\")");
    w.dedent();
    w.blank();

    // decode
    w.line("@classmethod");
    w.line(&format!("def decode(cls, data: bytes) -> \"{class_name}\":"));
    w.indent();
    w.line("raw = cbor2.loads(data)");
    if let Some(tag) = e.tagged {
        w.line(&format!("if not isinstance(raw, cbor2.CBORTag) or raw.tag != {}:", tag.0));
        w.indent();
        w.line("raise ValueError(\"Unexpected CBOR tag\")");
        w.dedent();
        w.line("raw = raw.value");
    }
    w.line("if isinstance(raw, str):");
    w.indent();
    w.line("match raw:");
    w.indent();
    for v in &e.variants {
        if matches!(&v.ty, TypeRef::Primitive(Primitive::Null | Primitive::Tstr)) {
            let vname    = to_pascal_case(&v.name);
            let cddl_str = v.name.to_lowercase().replace('_', "-");
            w.line(&format!("case {cddl_str:?}: return cls(kind={vname:?})"));
        }
    }
    w.line(&format!("case _: raise ValueError(f\"Unknown {class_name} variant: {{raw}}\")"));
    w.dedent();
    w.dedent();

    let has_int = e.variants.iter().any(|v|
        matches!(&v.ty, TypeRef::Primitive(Primitive::Uint | Primitive::Int)));
    if has_int {
        w.line("if isinstance(raw, int):");
        w.indent();
        for v in &e.variants {
            if matches!(&v.ty, TypeRef::Primitive(Primitive::Uint | Primitive::Int)) {
                let vname = to_pascal_case(&v.name);
                w.line(&format!("return cls(kind={vname:?}, value=raw)"));
                break;
            }
        }
        w.dedent();
    }
    w.line(&format!("raise ValueError(f\"Cannot decode {class_name}\")"));
    w.dedent();

    w.dedent();
}

// ── Array ─────────────────────────────────────────────────────────────────────

fn emit_array(w: &mut IndentWriter, a: &ArrayDef, opts: &CodegenOptions) {
    if let Some(doc) = a.doc.as_deref() { w.line(&format!("# {doc}")); }
    if a.deprecated { w.line("# @deprecated"); }

    let class_name = to_pascal_case(&a.name);
    let elem_ty    = py_typeref(&a.element, opts);

    w.line("@dataclass");
    w.line(&format!("class {class_name}:"));
    w.indent();
    w.line(&format!("items: list[{elem_ty}] = field(default_factory=list)"));
    w.blank();

    w.line("def encode(self) -> bytes:");
    w.indent();
    if let Some(tag) = a.tagged {
        w.line(&format!("return cbor2.dumps(cbor2.CBORTag({}, self.items))", tag.0));
    } else {
        w.line("return cbor2.dumps(self.items)");
    }
    w.dedent();
    w.blank();

    w.line("@classmethod");
    w.line(&format!("def decode(cls, data: bytes) -> \"{class_name}\":"));
    w.indent();
    w.line("raw = cbor2.loads(data)");
    if let Some(tag) = a.tagged {
        w.line(&format!("if not isinstance(raw, cbor2.CBORTag) or raw.tag != {}:", tag.0));
        w.indent();
        w.line("raise ValueError(\"Unexpected CBOR tag\")");
        w.dedent();
        w.line("raw = raw.value");
    }
    w.line("if not isinstance(raw, list):");
    w.indent();
    w.line("raise ValueError(\"Expected CBOR array\")");
    w.dedent();
    let conv = py_convert_expr(&a.element, "item", opts);
    w.line(&format!("return cls(items=[{conv} for item in raw])"));
    w.dedent();

    w.dedent();
}

// ── Alias ─────────────────────────────────────────────────────────────────────

fn emit_alias(w: &mut IndentWriter, a: &AliasDef, opts: &CodegenOptions) {
    if let Some(doc) = a.doc.as_deref() { w.line(&format!("# {doc}")); }
    if a.deprecated { w.line("# @deprecated"); }

    let class_name = to_pascal_case(&a.name);
    let inner_ty   = py_typeref(&a.ty, opts);

    w.line("@dataclass");
    w.line(&format!("class {class_name}:"));
    w.indent();
    w.line(&format!("value: {inner_ty}"));
    w.blank();

    if !a.constraints.is_empty() {
        w.line("def __post_init__(self) -> None:");
        w.indent();
        let mut any = false;
        for c in &a.constraints {
            if let Some(check) = py_constraint_check(c, "self.value") {
                let msg = py_constraint_description(c);
                w.line(&format!("if not ({check}):"));
                w.indent();
                w.line(&format!("raise ValueError({msg:?})"));
                w.dedent();
                any = true;
            }
        }
        if !any { w.line("pass"); }
        w.dedent();
        w.blank();
    }

    w.line("def encode(self) -> bytes:");
    w.indent();
    if let Some(tag) = a.tagged {
        w.line(&format!("return cbor2.dumps(cbor2.CBORTag({}, self.value))", tag.0));
    } else {
        w.line("return cbor2.dumps(self.value)");
    }
    w.dedent();
    w.blank();

    w.line("@classmethod");
    w.line(&format!("def decode(cls, data: bytes) -> \"{class_name}\":"));
    w.indent();
    w.line("raw = cbor2.loads(data)");
    if let Some(tag) = a.tagged {
        w.line(&format!("if not isinstance(raw, cbor2.CBORTag) or raw.tag != {}:", tag.0));
        w.indent();
        w.line("raise ValueError(\"Unexpected CBOR tag\")");
        w.dedent();
        w.line("raw = raw.value");
    }
    let conv = py_convert_expr(&a.ty, "raw", opts);
    w.line(&format!("return cls(value={conv})"));
    w.dedent();

    w.dedent();
}

// ── Constraint helpers ────────────────────────────────────────────────────────

fn py_constraint_check(c: &Constraint, expr: &str) -> Option<String> {
    match c {
        Constraint::SizeExact(n) => Some(format!("len({expr}) == {n}")),
        Constraint::SizeRange { min, max } => match (min, max) {
            (Some(lo), Some(hi)) => Some(format!("{lo} <= len({expr}) <= {hi}")),
            (Some(lo), None)     => Some(format!("len({expr}) >= {lo}")),
            (None, Some(hi))     => Some(format!("len({expr}) <= {hi}")),
            (None, None)         => None,
        },
        Constraint::ValueRangeInt { min, max, inclusive } => {
            let op = if *inclusive { "=" } else { "" };
            match (min, max) {
                (Some(lo), Some(hi)) => Some(format!("{lo} <{op}= {expr} <{op}= {hi}")),
                (Some(lo), None)     => Some(format!("{expr} >{op}= {lo}")),
                (None, Some(hi))     => Some(format!("{expr} <{op}= {hi}")),
                (None, None)         => None,
            }
        }
        Constraint::ValueRangeUint { min, max, inclusive } => {
            let op = if *inclusive { "=" } else { "" };
            match (min, max) {
                (Some(lo), Some(hi)) => Some(format!("{lo} <{op}= {expr} <{op}= {hi}")),
                (Some(lo), None)     => Some(format!("{expr} >{op}= {lo}")),
                (None, Some(hi))     => Some(format!("{expr} <{op}= {hi}")),
                (None, None)         => None,
            }
        }
        Constraint::Eq(v) => Some(format!("{expr} == {}", py_literal(v))),
        Constraint::Ne(v) => Some(format!("{expr} != {}", py_literal(v))),
        Constraint::Regexp { hook: Some(h), .. } => Some(format!("{h}({expr})")),
        _ => None,
    }
}

fn py_constraint_description(c: &Constraint) -> String {
    match c {
        Constraint::SizeExact(n)   => format!("length must be {n}"),
        Constraint::SizeRange { min, max } => format!("length out of range ({min:?}..{max:?})"),
        Constraint::ValueRangeInt { min, max, .. } => format!("value out of range ({min:?}..{max:?})"),
        Constraint::ValueRangeUint { min, max, .. } => format!("value out of range ({min:?}..{max:?})"),
        Constraint::Eq(v) => format!("must equal {}", py_literal(v)),
        Constraint::Ne(v) => format!("must not equal {}", py_literal(v)),
        _                 => "constraint violated".into(),
    }
}

fn py_literal(v: &LiteralValue) -> String {
    match v {
        LiteralValue::Bool(b)  => if *b { "True".into() } else { "False".into() },
        LiteralValue::Null     => "None".into(),
        LiteralValue::Uint(n)  => n.to_string(),
        LiteralValue::Int(n)   => n.to_string(),
        LiteralValue::Float(f) => f.to_string(),
        LiteralValue::Text(s)  => format!("{s:?}"),
        LiteralValue::Bytes(_) => "b\"\"".into(),
    }
}

// ── Convert expressions ───────────────────────────────────────────────────────

fn py_convert_expr(ty: &TypeRef, raw_expr: &str, opts: &CodegenOptions) -> String {
    match ty {
        TypeRef::Primitive(p)     => py_convert_primitive(p, raw_expr),
        TypeRef::Named(n)         => format!("{}.decode(cbor2.dumps({raw_expr}))", to_pascal_case(n)),
        TypeRef::Tagged(_, inner) => py_convert_expr(inner, raw_expr, opts),
        TypeRef::Choice(_)        => raw_expr.into(),
    }
}

fn py_convert_primitive(p: &Primitive, expr: &str) -> String {
    match p {
        Primitive::Uint | Primitive::Int => format!("int({expr})"),
        Primitive::Bool                  => format!("bool({expr})"),
        Primitive::Float32 | Primitive::Float16
        | Primitive::Float64 | Primitive::Float => format!("float({expr})"),
        Primitive::Tstr                  => format!("str({expr})"),
        Primitive::Bstr | Primitive::Any => format!("bytes({expr})"),
        Primitive::Null | Primitive::Undefined => "None".into(),
    }
}

// ── Python type helpers ───────────────────────────────────────────────────────

fn py_field_type(ty: &TypeRef, occ: &Occurrence, opts: &CodegenOptions) -> String {
    let base = py_typeref(ty, opts);
    match occ {
        Occurrence::Optional => format!("Optional[{base}]"),
        Occurrence::ZeroOrMore { .. } | Occurrence::OneOrMore { .. }
        | Occurrence::Bounded { .. } => format!("list[{base}]"),
        Occurrence::Required => base,
    }
}

fn py_typeref(ty: &TypeRef, opts: &CodegenOptions) -> String {
    match ty {
        TypeRef::Primitive(p)     => py_primitive(p).to_owned(),
        TypeRef::Named(n)         => to_pascal_case(n),
        TypeRef::Tagged(_, inner) => py_typeref(inner, opts),
        TypeRef::Choice(cs)       => {
            if cs.is_empty() { return "object".into(); }
            cs.iter().map(|c| py_typeref(c, opts))
              .collect::<Vec<_>>().join(" | ")
        }
    }
}

fn py_primitive(p: &Primitive) -> &'static str {
    match p {
        Primitive::Bool   => "bool",
        Primitive::Null | Primitive::Undefined => "None",
        Primitive::Uint | Primitive::Int => "int",
        Primitive::Float16 | Primitive::Float32
        | Primitive::Float64 | Primitive::Float => "float",
        Primitive::Tstr   => "str",
        Primitive::Bstr | Primitive::Any => "bytes",
    }
}

fn py_module_name(name: &str) -> String {
    name.replace('-', "_")
}

// ── Test file ─────────────────────────────────────────────────────────────────

fn emit_tests(module: &IrModule, opts: &CodegenOptions) -> String {
    let name     = module.name.as_str();
    let mod_name = py_module_name(name);
    let mut w    = IndentWriter::new(4);

    w.line("# @generated by cddlc — do not edit manually");
    w.line("import pytest");
    w.line(&format!("from {mod_name} import ("));
    w.indent();
    for (_, def) in &module.types {
        w.line(&format!("{},", to_pascal_case(def.name())));
    }
    w.dedent();
    w.line(")");
    w.blank();

    for (_, def) in &module.types {
        emit_type_tests(&mut w, def, opts);
        w.blank();
    }

    w.finish()
}

fn emit_type_tests(w: &mut IndentWriter, def: &TypeDef, opts: &CodegenOptions) {
    match def {
        TypeDef::Struct(s) => emit_struct_tests(w, s, opts),
        TypeDef::Enum(e)   => emit_enum_tests(w, e),
        TypeDef::Alias(a)  => emit_alias_tests(w, a, opts),
        TypeDef::Array(a)  => emit_array_tests(w, a),
        TypeDef::Map(_)    => {}
    }
}

fn emit_struct_tests(w: &mut IndentWriter, s: &StructDef, opts: &CodegenOptions) {
    let class_name = to_pascal_case(&s.name);
    let _fn_pfx    = to_snake_case(&s.name);

    w.line(&format!("class Test{class_name}:"));
    w.indent();

    w.line("def test_roundtrip_default(self):");
    w.indent();
    w.line(&format!("original = {class_name}("));
    w.indent();
    for f in &s.fields {
        let fname = to_snake_case(&f.name);
        let val   = py_default_value(&f.ty, &f.occurrence, opts);
        w.line(&format!("{fname}={val},"));
    }
    w.dedent();
    w.line(")");
    w.line(&format!("decoded = {class_name}.decode(original.encode())"));
    for f in &s.fields {
        let fname = to_snake_case(&f.name);
        w.line(&format!("assert decoded.{fname} == original.{fname}"));
    }
    w.dedent();
    w.blank();

    w.line("def test_roundtrip_explicit(self):");
    w.indent();
    w.line(&format!("original = {class_name}("));
    w.indent();
    for f in &s.fields {
        let fname = to_snake_case(&f.name);
        let val   = py_explicit_value(&f.ty, &f.occurrence, opts);
        w.line(&format!("{fname}={val},"));
    }
    w.dedent();
    w.line(")");
    w.line(&format!("decoded = {class_name}.decode(original.encode())"));
    for f in &s.fields {
        let fname = to_snake_case(&f.name);
        w.line(&format!("assert decoded.{fname} == original.{fname}"));
    }
    w.dedent();

    if s.tagged.is_some() {
        w.blank();
        w.line(&format!("def test_encode_has_tag(self):"));
        w.indent();
        w.line(&format!("obj = {class_name}("));
        w.indent();
        for f in &s.fields {
            let fname = to_snake_case(&f.name);
            let val   = py_default_value(&f.ty, &f.occurrence, opts);
            w.line(&format!("{fname}={val},"));
        }
        w.dedent();
        w.line(")");
        w.line("assert len(obj.encode()) > 0");
        w.dedent();
    }

    w.dedent();
}

fn emit_enum_tests(w: &mut IndentWriter, e: &EnumDef) {
    let class_name = to_pascal_case(&e.name);

    w.line(&format!("class Test{class_name}:"));
    w.indent();

    for v in &e.variants {
        let vname    = to_pascal_case(&v.name);
        let fn_name  = to_snake_case(&v.name);
        let construct = match &v.ty {
            TypeRef::Primitive(Primitive::Null | Primitive::Tstr) =>
                format!("{class_name}.make_{vname}()"),
            TypeRef::Primitive(Primitive::Uint | Primitive::Int) =>
                format!("{class_name}.make_{vname}(0)"),
            TypeRef::Primitive(Primitive::Bool) =>
                format!("{class_name}.make_{vname}(False)"),
            _ => format!("{class_name}.make_{vname}()"),
        };

        w.line(&format!("def test_roundtrip_{fn_name}(self):"));
        w.indent();
        w.line(&format!("original = {construct}"));
        w.line(&format!("decoded = {class_name}.decode(original.encode())"));
        w.line("assert decoded.kind == original.kind");
        w.dedent();
        w.blank();
    }

    w.dedent();
}

fn emit_alias_tests(w: &mut IndentWriter, a: &AliasDef, opts: &CodegenOptions) {
    let class_name = to_pascal_case(&a.name);
    let valid_val  = py_valid_constrained_value(&a.constraints, &a.ty, opts);

    w.line(&format!("class Test{class_name}:"));
    w.indent();

    w.line("def test_roundtrip_valid(self):");
    w.indent();
    w.line(&format!("original = {class_name}(value={valid_val})"));
    w.line(&format!("decoded = {class_name}.decode(original.encode())"));
    w.line("assert decoded.value == original.value");
    w.dedent();

    if !a.constraints.is_empty() {
        w.blank();
        let bad_val = py_invalid_constrained_value(&a.constraints, &a.ty, opts);
        w.line("def test_invalid_raises(self):");
        w.indent();
        w.line("with pytest.raises(ValueError):");
        w.indent();
        w.line(&format!("{class_name}(value={bad_val})"));
        w.dedent();
        w.dedent();
    }

    w.dedent();
}

fn emit_array_tests(w: &mut IndentWriter, a: &ArrayDef) {
    let class_name = to_pascal_case(&a.name);

    w.line(&format!("class Test{class_name}:"));
    w.indent();

    w.line("def test_roundtrip_empty(self):");
    w.indent();
    w.line(&format!("original = {class_name}()"));
    w.line(&format!("decoded = {class_name}.decode(original.encode())"));
    w.line("assert decoded.items == original.items");
    w.dedent();

    w.dedent();
}

// ── Test value helpers ────────────────────────────────────────────────────────

fn py_default_value(ty: &TypeRef, occ: &Occurrence, _opts: &CodegenOptions) -> String {
    match occ {
        Occurrence::Optional => "None".into(),
        Occurrence::ZeroOrMore { .. } | Occurrence::OneOrMore { .. }
        | Occurrence::Bounded { .. } => "[]".into(),
        Occurrence::Required => match ty {
            TypeRef::Primitive(Primitive::Uint | Primitive::Int) => "0".into(),
            TypeRef::Primitive(Primitive::Bool) => "False".into(),
            TypeRef::Primitive(Primitive::Float32 | Primitive::Float16
                | Primitive::Float64 | Primitive::Float) => "0.0".into(),
            TypeRef::Primitive(Primitive::Tstr) => "\"\"".into(),
            TypeRef::Primitive(Primitive::Bstr | Primitive::Any) => "b\"\"".into(),
            TypeRef::Primitive(Primitive::Null | Primitive::Undefined) => "None".into(),
            TypeRef::Named(n) => format!("{}(value=0)", to_pascal_case(n)),
            _ => "None".into(),
        },
    }
}

fn py_explicit_value(ty: &TypeRef, occ: &Occurrence, opts: &CodegenOptions) -> String {
    match occ {
        Occurrence::Optional => "None".into(),
        Occurrence::ZeroOrMore { .. } | Occurrence::OneOrMore { .. }
        | Occurrence::Bounded { .. } => "[]".into(),
        Occurrence::Required => match ty {
            TypeRef::Primitive(Primitive::Uint) => "42".into(),
            TypeRef::Primitive(Primitive::Int)  => "-1".into(),
            TypeRef::Primitive(Primitive::Bool) => "True".into(),
            TypeRef::Primitive(Primitive::Float32 | Primitive::Float16
                | Primitive::Float64 | Primitive::Float) => "3.14".into(),
            TypeRef::Primitive(Primitive::Tstr)  => "\"hello\"".into(),
            TypeRef::Primitive(Primitive::Bstr | Primitive::Any) => "b\"\\x01\\x02\"".into(),
            _ => py_default_value(ty, occ, opts),
        },
    }
}

fn py_valid_constrained_value(constraints: &[Constraint], ty: &TypeRef, opts: &CodegenOptions) -> String {
    for c in constraints {
        match c {
            Constraint::SizeExact(n) => match ty {
                TypeRef::Primitive(Primitive::Tstr) => return format!("\"a\" * {n}"),
                TypeRef::Primitive(Primitive::Bstr) => return format!("b\"\\x00\" * {n}"),
                _ => {}
            },
            Constraint::ValueRangeInt { min, .. } => {
                if let Some(lo) = min { return lo.to_string(); }
            }
            Constraint::ValueRangeUint { min, .. } => {
                if let Some(lo) = min { return lo.to_string(); }
            }
            _ => {}
        }
    }
    py_default_value(ty, &Occurrence::Required, opts)
}

fn py_invalid_constrained_value(constraints: &[Constraint], ty: &TypeRef, _opts: &CodegenOptions) -> String {
    for c in constraints {
        match c {
            Constraint::SizeExact(n) => match ty {
                TypeRef::Primitive(Primitive::Tstr) => return format!("\"a\" * ({n} + 1)"),
                TypeRef::Primitive(Primitive::Bstr) => return format!("b\"\\x00\" * ({n} + 1)"),
                _ => {}
            },
            Constraint::ValueRangeInt { min, .. } => {
                if let Some(lo) = min { return format!("{}", lo - 1); }
            }
            Constraint::ValueRangeUint { min, .. } => {
                if let Some(lo) = min {
                    if *lo > 0 { return format!("{}", lo - 1); }
                }
            }
            _ => {}
        }
    }
    "None".into()
}
